# Generated by Django 4.1.3 on 2022-11-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
